### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by is06** [ooga/ScrumBoard-it#18]
It's impossible to log in with the application.
Despite the fact that we have to go on /login route manually (no redirection is set on /), when I try to log in with my credentials, I have a "Incorrect login and/or password" error message.
Moreover, the configuration example of security.yml in the documentation is wrong, provider and firewall sections are plural, not singular, that causes errors...
Master branch should be stable...

**Comment by alcalyn** [comment]
I got this problem, maybe same:

On configuration:
```
canal_tp_scrum_board_it:
    jira_url:  http://jira.canaltp.fr/
    sprint_id: 143
```

`jira_url` *MUST* end with a slash

**Comment by alcalyn** [comment]
For security, this one works:
``` yml
security:
    provider:
        name: jira_auth_provider
        id: canaltp_jira_auth.user_provider
    firewall:
            name: jira_secured
            pattern: /
            switch_user: false
            context:     user
            provider: jira_auth_provider
            jira:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /login
            remember_me:
                key: "%secret%"
                lifetime: 300
                path: /.*
                domain: ~
            anonymous: ~
```
